### PR TITLE
Update fn_boltcutter.sqf

### PR DESCRIPTION
**Pull request by fresqo**
Resolves #<issue ID here>. 

#### Changes proposed in this pull request: 
- there was no timer for the Tanoa vault door

### CODE REVIEW

**Comment by BoGuu** [comment]
Have you actually verified there is no timer? I made this on purpose, it should be ```_cpRate = 0.0015```

See https://en.wikipedia.org/wiki/Switch_statement#Fallthrough

**Comment by fresqo** [comment]
oh i thought it was an error will test when i get home.
but wouldnt it have to look like this...
> switch (typeOf _building) do {
    case "Land_Dome_Big_F": {_cpRate = 0.003;};
    case "Land_Medevac_house_V1_F": 
    case "Land_Research_house_V1_F": {_cpRate = 0.0015;};
    break;
    default {_cpRate = 0.08;}
};

**Comment by BoGuu** [comment]
Depends how many errors you like! ;) You don't want it to start executing at that case, which the semi colon would allow it to.

**Comment by fresqo** [comment]
ok checked your way works sorry .. my mistake..

**Pull request closed without merging**
