### PR TITLE
Mission update WIP

### LINKED ISSUE #24: gang hideout 3
no access to get inside building after capturing, i guess someone bought it?

### PR DESCRIPTION
**Pull request by Heavybob**
Resolves #24 #44

#### Changes proposed in this pull request: 
- 

Moved Hospital_3 to Georgetown
images akamai steamusercontent

Updated Gang Hideout 3 with Land_Barracks_01_camo_F
107410_screenshots_20160809131703_1

*This is WIP, additional input would be good to progress this commit.

### CODE REVIEW

**Comment by setoy** [comment]
Haven't you forgot to add `Land_Barracks_01_camo_F` to [captureHideout.sqf](https://github.com/AsYetUntitled/Framework/blob/master/Altis_Life.Altis/core/actions/fn_captureHideout.sqf#L11)?

**Comment by Heavybob** [comment]
Clearly says WIP.

**Comment by setoy** [comment]
Clearly was just a heads up...

**Comment by trinitynet** [comment]
"*This is WIP, additional input would be good to progress this commit."

"Haven't you forgot to add Land_Barracks_01_camo_F to captureHideout.sqf?"

seriously? wtf is wrong with people....

**Comment by BoGuu** [comment]
Any news?

**Pull request closed without merging**
