### PR TITLE
Fixed Not-In-Gang ATM Money Disappearing

### LINKED ISSUE #290: Money Disappearing when Using Gang Deposit and not in a Gang
<Please review the guidelines for contributing to this repository. The link is above.>
<If you are reporting a bug then you must use the provided issue template.>

### Expected behavior
Player Attempts to use the "Deposit Gang" button, but the script ends and doesn't execute if they aren't in a game. Their balance stays the same.

### Actual behavior
When players press the "Deposit Gang" option, money is deleted from their account and it displays the "Success" message. 

### Steps to reproduce the behaviour 
1. Open ATM 
2. Have Money (Cash Or Bank)
3. Enter a value and deposit in gang
4. Money disappears

### [RPT](https://community.bistudio.com/wiki/Crash_Files#Arma_3) and/or extDB3 logs (if applicable)
Not Relevant

----

Mission version: Latest from master branch

```
Launcher version: 1.5.139565

Game version: 1.66.139586

Branch: main / beta branch not specified
```

### Possible Fix:
See #291

### PR DESCRIPTION
**Pull request by BradenJM**
Stops player from depositing money into a non existant gang. Causing
money to disappear.

<Please review the guidelines for contributing to this repository. The link is above.>

Resolves #290

#### Changes proposed in this pull request: 
- Adds checks in both `fn_gangDeposit.sqf` and `fn_gangWithdraw.sqf` to see if player is not in a gang. Exits if true.
- Adds entry to stringtable

### CODE REVIEW

**Comment by BoGuu** [comment]
Has this ever happened to you?

Either way, LGTM, could prevent an issue, thanks 👍 

Will wait a bit on the non English speakers to take a look at the stringtable first

**Comment by ThePistachios** [comment]
It was discovered when I was creating a different ATM menu and accidentally mixed up the normal deposit and gang deposit text (Yeah, I'm not too sure how I managed that). Tested it on vanilla and the bug was still there. 

No problem.

**Comment by Dim2ke** [comment]
This is a good check but how a player can deposit or withdraw money from the gang while the button is disabled 

file: fn_atmMenu.sqf
Line: 40-43
```
if (isNil {(group player getVariable "gang_bank")}) then {
    (CONTROL(2700,2705)) ctrlEnable false;
    (CONTROL(2700,2706)) ctrlEnable false;
};

```

**Comment by BradenJM** [comment]
@Dim2ke I am pretty sure that's broken on the latest commit. Would have to check to be sure. Otherwise, this may impact people who wish to create custom menus.

**Comment by Dim2ke** [comment]
@BradenJM I have just downloaded the latest version of a main and i have tested, the buttons are disabled [screenshot](https://gyazo.com/28c6728547232a5a03b1a448401a1d95)
I think your check would be good in back in case the first one would be broken but without the hint (check with dev).
When you create your custom menu, you can assign an id to the button and either deactivate them with "ctrlEnable" or hide them with "ctrlShow"

**Comment by BradenJM** [comment]
@Dim2ke Interesting. I must have broken them in my own version. When I did my "vanilla" testing I used my own ATM menu (So not really vanilla I suppose) ... I must have changed the IDs. Either way, up to people with write permissions if they wish to reject it or not. 👍

**Comment by BoGuu** [comment]
LGTM @Jawshy

**Comment by BoGuu** [comment]
Thanks! :)

**Pull request merged**
