### PR TITLE
ActionKeyHandler Fixes

### PR DESCRIPTION
**Pull request by harmdhast**
#### **Changes proposed in this pull request:**

> • Allow cops to use the ATMs with the action key (Windows or custom user key 10)
> • Side check for cop menu (Fix for civilian admin escort on some admin menus)
> • I don't know why it was handled that way tbh

### CODE REVIEW

**Comment by BoGuu** [comment]
Calling the cop interaction menu for any escorters is indeed bad design, but obviously not an issue with the code base (just external as you said). Do you think ATMs should take precedence over the interaction menu?

**Comment by harmdhast** [comment]
In my dream world we would get rid of the addActions. And allowing cops to use the same ATMs as the civilians seems logic to me. Server admins tends to forget to add the ATM code in the editor-placed ones and you can't access map / world placed ATM without the cursorTarget / cursorObject. (You still can get the ATM positions from the cfgWorld then use nearestObject to add an action but yeah, i don't think everyone can do that).
That's just my thoughts anyway.

**Comment by BoGuu** [comment]
>And allowing cops to use the same ATMs as the civilians seems logic to me
This code is just stopping them using the ATM while escorting someone, what do you mean exactly?

Currently any editor placed ATM's will be accessible via the action key without an addAction.

**Comment by harmdhast** [comment]
I don't think you understand
```
player getVariable ["isEscorting",false]; // When cop is not escorting then trigger the menu
```
I doesn't seems logical to me or I missunderstood. Tell me.

**Comment by BoGuu** [comment]
`player getVariable ["isEscorting", false]`

Will return true if the person is escorting someone. The false is purely there to avoid undefined errors. Take a look at the getVariable wiki page if you're confused

**Comment by harmdhast** [comment]
Wow my brain melted beetween setVariable and getVariable.
There's still the side check tbh.

**Comment by harmdhast** [comment]
Btw BoGuu is there any way I can contact you personnaly ? (Discord / Skype ?)

**Comment by BoGuu** [comment]
@harmdhast

I'm currently on holiday, but that looks better. Could you add lazy eval to it before merge?

You can contact me on discord. There is a link to a server I'm in on the README

**Pull request closed without merging**
