### PR TITLE
Update fn_setupActions.sqf

### PR DESCRIPTION
**Pull request by SMZAVGSERVERS**
**Changes proposed in this pull request:** 
- adding support for west & independent sides.

### CODE REVIEW

**Comment by SimZor** [comment]
Why would you add two cases that are not used? 🤔

**Comment by SMZAVGSERVERS** [comment]
@SimZor To make customisation easier ^^
That's not important but it's better than nothing :p

**Comment by SimZor** [comment]
They can just add it in themselves?

**Comment by SMZAVGSERVERS** [comment]
@SimZor Yep, ik but... i'm bored today u know x)

**Comment by SimZor** [comment]
You will also check for unnecessary playerSide, which means you are adding performance decrease in the framework.

**Comment by BoGuu** [comment]
This will become deprecated regardless soon :)

**Pull request merged**
