### PR TITLE
Drop Procedure for deleteOldWanted

### PR DESCRIPTION
**Pull request by DarkSilencerZA**

### CODE REVIEW

**Comment by Jawshy** [comment]
LGTM

**Comment by Jawshy** [comment]
> No description provided.

Something, something, pull request template, @DarkSilencerZA.

**Comment by DarkSilencerZA** [comment]
Merge it already..

**Comment by BoGuu** [comment]
LGTM

It's there for a reason, use it. @DarkSilencerZA

**Pull request merged**
