### PR TITLE
Kron & init cleanup 

### PR DESCRIPTION
**Pull request by DomT602**
Resolves N/A. 

#### Changes proposed in this pull request: 
- Replaces KRON functionality with newer commands
- Cleans up init related

- [x] I have tested my changes and corrected any errors found

### CODE REVIEW

**Comment by moeck** [comment]
if I try to acess the trunk it ist not possible to get things out. Error message "wrong number format"

**Comment by DomT602** [comment]
Good find, I forgot to remove the str surrounding _x for the isNumber function, that’ll be the issue

**Comment by moeck** [comment]
you are right, I changed it in the life_server\functions.sqf and it works for me

**Comment by Jason2605** [comment]
Good spot thanks, I've updated the main branch now!

**Pull request merged**
