### PR TITLE
Gang Store Consistency

### PR DESCRIPTION
**Pull request by J4Wx**
On each map, the first gang store encountered does not include the additional arguments for nearestObjects, resulting in issues with the store if additional items have been placed.

#### Changes proposed in this pull request: 
- Add these additional arguments to the gang store missing them.

### CODE REVIEW

**Comment by BoGuu** [comment]
LGTM, thanks

**Comment by WolfSkin1337** [comment]
thanks, but when we do consistency then we can make the change too at following Lines:
`Altis`
https://github.com/AsYetUntitled/Framework/blob/master/SQMs/missionAltis.sqm#L19872
https://github.com/AsYetUntitled/Framework/blob/master/SQMs/missionAltis.sqm#L21111
https://github.com/AsYetUntitled/Framework/blob/master/SQMs/missionAltis.sqm#L22267
https://github.com/AsYetUntitled/Framework/blob/master/SQMs/missionAltis.sqm#L22349
https://github.com/AsYetUntitled/Framework/blob/master/SQMs/missionAltis.sqm#L23504

`Tanoa`
https://github.com/AsYetUntitled/Framework/blob/master/SQMs/missionTanoa.sqm#5674
https://github.com/AsYetUntitled/Framework/blob/master/SQMs/missionTanoa.sqm#6550
https://github.com/AsYetUntitled/Framework/blob/master/SQMs/missionTanoa.sqm#7337
https://github.com/AsYetUntitled/Framework/blob/master/SQMs/missionTanoa.sqm#7420
https://github.com/AsYetUntitled/Framework/blob/master/SQMs/missionTanoa.sqm#8373

Or not?

**Comment by BoGuu** [comment]
I can see that this could be an issue, but I'm wondering what objects that class as buildings are exactly causing the issues? Unless you place things further away from the hideout itself. Can you confirm?

**Comment by BoGuu** [comment]
LGTM, thanks :)

**Pull request merged**
