### PR TITLE
Whitelisted Terrain Sorting Function (SpyGlass)

### PR DESCRIPTION
**Pull request by SimZor**

### CODE REVIEW

**Comment by Jawshy** [comment]
Was it just `life_fnc_terrainsort` that was added to `LIFE_Functions`? Could you please sort it alphabetically for consistency? You can use [this web tool](http://www.textfixer.com/tools/alphabetical-order.php).

**Comment by SimZor** [comment]
I'll do that. It was just ```life_fnc_terrainsort``` to LIFE_Functions.

**Comment by SimZor** [comment]
@Jawshy Alphabetical Done and also removed serv_wanted_remove.

**Comment by BoGuu** [comment]
Cheers :+1:

**Pull request merged**
