### PR TITLE
Admin Markers

### LINKED ISSUE #292: Admin Markers not disappearing
### Expected behaviour
When clicked on Markers in the Admin Menu, all map markers should disappear.

### Actual behaviour
They do not disappear, in fact in some cases they somehow get duplicated.

### Steps to reproduce the behaviour 
1. Open admin menu and click markers

### [RPT](https://community.bistudio.com/wiki/Crash_Files#Arma_3) and/or extDB3 logs (if applicable)
No Errors in client/server

----

Mission version: 5.0.0

Launcher version: 1.5.139565

Game version: 1.66.139586

Branch: main

### PR DESCRIPTION
**Pull request by Jason2605**
# Admin Markers

Resolves #292

#### Changes proposed in this pull request: 
- Very simple re-work of how the Admin Markers work.

- [x] I have tested my changes and corrected any errors found

### CODE REVIEW

**Comment by BoGuu** [comment]
visibleMap and more preferably the new map EVH :)

**Comment by BlackFisch** [comment]
looks good to me :) but you should also remove `"ton_fnc_mapmarkersadmin"` from Config_SpyGlass since you removed that function ^^

**Comment by Jason2605** [comment]
Yep good spot, will remove it soon.

**Comment by SimZor** [comment]
To be completely honest, just use Draw EVH and and then ``drawIcon`` command instead. IMO drawIcon in OEF (Draw) EVH produces much cleaner code.

**Comment by SimZor** [comment]
For reference:

https://community.bistudio.com/wiki/Arma_3:_Event_Handlers/addMissionEventHandler#EachFrame
https://community.bistudio.com/wiki/drawIcon

**Comment by Jason2605** [comment]
Ended up pushing to the wrong branch, will re-submit PR

**Pull request closed without merging**
