### PR TITLE
Fix endoftheline error

### PR DESCRIPTION
**Pull request by Casperento**
#### Changes proposed in this pull request: 
- Fix endoftheline.sqf error before everything blows up

- [x] I have tested my changes and corrected any errors found

### CODE REVIEW

**Comment by Casperento** [comment]
Waiting to this PR get approved so i can add the new ones regarding headgear and briefing' updates

**Comment by BlackFisch** [comment]
@DomT602 @BoGuu

**Comment by BoGuu** [comment]
Just remove the header

**Comment by Casperento** [comment]
Done!

**Pull request merged**
