### PR TITLE
Make all Tabs to spaces at the Framework

### PR DESCRIPTION
**Pull request by WolfSkin1337**
#### Changes proposed in this pull request: 
- change all last Tabs to Spaces

### CODE REVIEW

**Comment by WolfSkin1337** [comment]
If I have done something wrong, please let me know

**Comment by Angrygargamel** [comment]
just for my interest...
why should we change a tab to spaces at all?

**Comment by DarkSilencerZA** [comment]
IMO its retarded. Tabs take up way less space. Stick to tabs.

**Comment by BoGuu** [comment]
This will break SpyGlass if you change it, so please take that out.

@Angrygargamel Google around about tabs vs spaces for open source projects, not having another conversation about it ;)

**Comment by WolfSkin1337** [comment]
@BoGuu Which file or which line exactly should I not change?

**Comment by BoGuu** [comment]
The displays in SpyGlass (the big forEach's). Also the scripts.txt

**Comment by WolfSkin1337** [comment]
@BoGuu you mean this files? all ok?

**Comment by Jawshy** [comment]
> just for my interest...
why should we change a tab to spaces at all? 

@Angrygargamel, below is the email transcript of the original discussion about using tabs or spaces. My post(s) are not visible because I was not receiving notifications my own updates at that time. 

[[ArmaLife/Framework] Spacing Guideline (#646)](https://cloud.githubusercontent.com/assets/10876578/22006749/670e19b6-dcb9-11e6-8237-9bf44dadce03.png)

**Comment by Angrygargamel** [comment]
oh man... i guess the saying "too many cooks spoil the broth" fits very well on stuff like that

dont get me wrong... i wont tell anyone how to format his code
but imho the discussion is nonsense

**Comment by BoGuu** [comment]
@Angrygargamel 

Before we set a standard for contributions, there was a wide variety of indentation being committed, which caused massive issues (it may look normal on your screen, but on the repo it was completely random). On top of this, there is benefits to using spaces of tabs, of which the internet should tell you :P

**Comment by BoGuu** [comment]
LGTM

**Pull request merged**
