### PR TITLE
[master] fix variable shadowing in fn_fuelSupply

### PR DESCRIPTION
**Pull request by shazoo-o**
#### Changes proposed in this pull request: 
- block-local _fuelFeedState in line 48 shadows global _fuelFeedState in line 40
to prevent shadowing block-local variable was renamed
- additional else-block to set outer _fuelFeedState when fuel station wasn't fully refilled

- [x] I have tested my changes and corrected any errors found

### CODE REVIEW

**Comment by BlackFisch** [comment]
This isn't a real issue, since it's declared inside the if andd thus it's another scope - the other variable isn't tempered with by that
For readability though - I approve :D

**Comment by shazoo-o** [comment]
I've tested it quite well.
The issue is this: https://en.wikipedia.org/wiki/Variable_shadowing

How it fails:

1. On the first run line 43 returns the default empty array as the member fuelTank does not yet exists for this fuel pump. Then line 46 sets _fuelFeedState to the random value so line 59 is passed this first time.
2. On every other run later fuelTank is already defined so the else block is executed. The params[] then creates a new additional _fuelFeedSate which shadows the one declared in line 40. As the outer one in line 40 then is never changed again the if() on line 59 always triggers and cause exitWith().
3. The additional else block on line 54 is required for the same reason: If the fuel station isn't fully refilled the _fuelFeedState of the current line 48 shadows the one from line 40 so the current fuel level never gets to line 59 which again result in exitWith() is always triggered.

Sorry I couldn't come up with a better new name, but it shouldn't matter much.

**Comment by BlackFisch** [comment]
Oh, I see the problem :D didn't recognize this on the phone ^^ Good spot!

**Comment by shazoo-o** [comment]
fix for 5.x.x in #705

**Pull request merged**
