### PR TITLE
Update stringtable.xml

### LINKED ISSUE #176: Error in stringtable
<Please review the guidelines for contributing to this repository. The link is above.>
<If you are reporting a bug then you must use the provided issue template.>

### Expected behaviour
Returning names of crimes

### Actual behaviour
Not returning names of crimes

### Steps to reproduce the behaviour 
Done nothing, by default.

### [RPT](https://community.bistudio.com/wiki/Crash_Files#Arma_3) and/or extDB2 logs (if applicable)
No RPT

###Explanation
In stringtable, STR_Wanted_Count.
`<French>%1 chef (s) de 2%/French>`
have to be changed to
`<French>%1 chef (s) de %2</French>`

`<Italian>%1 count (s) del 2%</Italian>`
have to be changed to
`<Italian>%1 count (s) del %2</Italian>` (Thanks to @Lokiro67)

Also, if you are needing a French guy who wants to traduct stringtable, I'm free ATM :)
----

Mission version: 4.5(only tested in 4.5)

Launcher version: 1.5.138680

Game version: 1.64.138732

Branch: main / beta branch not specified

### PR DESCRIPTION
**Pull request by Lokiro67**
Resolves #176  

#### Changes proposed in this pull request: 
- patch minor error with wanted translated

Edit: Resolves https://github.com/AsYetUntitled/Framework/issues/176 -- @Jawshy

### CODE REVIEW

**Comment by Jawshy** [comment]
Thanks for the pull request, @Lokiro67, but in future please follow the provided [pull request template](https://raw.githubusercontent.com/AsYetUntitled/Framework/master/.github/PULL_REQUEST_TEMPLATE.md).

**Comment by Lokiro67** [comment]
sorry for the pull request template. next time i follow it :)

**Comment by Jawshy** [comment]
@Lokiro67, I found some more fixes, but I cannot push them to your `Lokiro67:patch-2` branch because it is [protected](https://help.github.com/articles/about-protected-branches/). Could you please unprotect the branch or replace the file with the file below? 
[stringtable.zip](https://github.com/AsYetUntitled/Framework/files/596493/stringtable.zip)

**Comment by Lokiro67** [comment]
yeah its unprotected and updated with your file. sorry I do not know too much how github still works im working for understand ^^

**Comment by BoGuu** [comment]
We have an issues with huge conflicts about to happen, I think.

**Comment by Jawshy** [comment]
LGTM

**Comment by BoGuu** [comment]
LGTM

**Pull request merged**
