### PR TITLE
Apex content

### PR DESCRIPTION
**Pull request by jcbjoe**
Added pretty much all the needed apex content. The overpowered and
unessasary things arnt in I.E Lynx.
- Vehicles
- Clothing and Hats
- Weapons - Damn PM 9mm mag

Thanks to WIlDott for helping me

### CODE REVIEW

**Comment by BoGuu** [comment]
What's happened?

**Comment by jcbjoe** [comment]
I noticed that the hummingbird commits were in here with my apex amendments. I closed it trying to fix this but was uncusessfull. I know what I did wrong and on my next requests this won't happen. Sorry. I mad a new request #61

**Comment by BoGuu** [comment]
No problem, I'll be merging everything tomorrow, off to bed :)

**Comment by jcbjoe** [comment]
Alright bud :) thanks

**Pull request closed without merging**
