### PR TITLE
Vehicle Virtual Inventory Dupefix

### LINKED ISSUE #339: Vehicle virtual inventory dupe
### Expected behaviour
<What should have happened?>

### Actual behaviour
<What actually happened?>

Two people can open the virtual baggage of the vehicle at the same time.

### Steps to reproduce the behaviour 
1. <How did you break it?>

Only one person open baggage,
The other person must be away to open the baggage.

Mission version: 5

### PR DESCRIPTION
**Pull request by C0kkie**
Resolves #339

#### Changes proposed in this pull request: 
- Fixes this dupe https://github.com/AsYetUntitled/Framework/issues/339

- We used this system on our server and it works very fine

### CODE REVIEW

**Comment by SalihF7** [comment]
I have tested and 
1- 2 people open at the same time vehicle inventory
2- Start counting back from 5
3- When the countdown is over, 1 person closes the modems and attracts the item.
result : item comes in 2 people

**Comment by SimZor** [comment]
This will not fix it. You need to use eventhandlers over the network.

**Comment by SalihF7** [comment]
@SimZor how to use it over the network I don't understand

**Comment by DomT602** [comment]
As the fork has been deleted, and the issue could still occur, this PR will be closed.

**Comment by akane777222** [comment]
This issue is not resolved and you can still open your inventory at the same time with 2 people.

**Pull request closed without merging**
