### PR TITLE
Added paving for hospital

### PR DESCRIPTION
**Pull request by SPS6**
Spawns brick paving to front of hospital level with garage and steps of reception area.

https://steamuserimages-a.akamaihd.net/ugc/804299863465234407/1611CB545D3898ADAB4ACDE3E6B442F95CE12EA5/

<Please review the guidelines for contributing to this repository. The link is above.>

Resolves #<issue ID here>. <If applicable.>

#### Changes proposed in this pull request: 
-

### CODE REVIEW

**Comment by ShadowRanger** [comment]
Just a heads up, these pavements are an asset of Arma 3 Apex, so people without it won't be able to see them and it may (not 100% sure) cause issues with people being able to join the server, but because this is created through a script, and not actually in the mission it shouldn't do so.

**Comment by SPS6** [comment]
good point, i might make one using the pier boxes too, the bricks look so pretty though

**Comment by ShadowRanger** [comment]
You could do one for Altis, and the other one for Tanoa. Just add in a simple check for what map it is.

**Comment by danielstuart14** [comment]
why?

**Comment by SPS6** [comment]
I suppose in case people would prefer the pier boxes? or is that not what your one word question was asking?

**Comment by danielstuart14** [comment]
why add that?

**Comment by SimZor** [comment]
rofl

**Comment by danielstuart14** [comment]
Does it need to be "fixed"? No
Does it add any new functionality? No
Does it make the gameplay more enjoyable? No
Does it add more unnecessary objects to the map? Yes (We want to keep FPS happy, right?)

I condensed these and much more questions in just an "why", sorry about that.

**Comment by SPS6** [comment]
I did it on my server to get rid of having dirt and grass leading from the road to the hospital and BoGuu asked me to make a pull request with the edits I made, I didn't realise you were going to just attempt to ridicule me.

**Comment by danielstuart14** [comment]
I'm not attempting anything man

**Comment by imKLM** [comment]
was a non-functioning phone menu necessary for the framework? :kappa:

**Comment by danielstuart14** [comment]
that was a wip phone that I never got time to finish. (It wasn't even in this repo)
But, yes, that old phone is an example of something that shouldn't be merged in a pull-request.

**Pull request closed without merging**
