### PR TITLE
Removed public slots and edited the admin access

### PR DESCRIPTION
**Pull request by gitAlexDE**
Public slots and admin access (fn_initCop.sqf)
- public slots removed
- admin query edited
 -> If you want allow your admins to use the slots then you need to edit "admin_slotAccessAllowed_COP" in the Config_Master.hpp to true.

admin access (fn_initMedic.sqf)
- admin query edited
 -> If you want allow your admins to use the slots then you need to edit "admin_slotAccessAllowed_MEDIC" in the Config_Master.hpp to true.

admin access (Config_Master.hpp)
added
- admin_slotAccessAllowed_COP
- admin_slotAccessAllowed_MEDIC

- [yes] I have tested my changes and corrected any errors found

### CODE REVIEW

**Comment by AWildTeddyBear** [comment]
I think this would be moreof a personal change and not something for the official repo. ;P

**Comment by gitAlexDE** [comment]
It might be a personal but with this change you can decide what you want, so i think it isn't a bad idea for the official repo.

**Comment by AWildTeddyBear** [comment]
The repo is designed for "you can decide what you want" tho. 🤔

**Comment by ToxicRageTv** [comment]
why not add an option in the master_config for public cops

**Comment by AWildTeddyBear** [comment]
Because it's a framework designed to be changed to user's needs? 🤔

**Comment by gitAlexDE** [comment]
I understand your point of view, but then some decisions in Config_Master.hpp would not even exist. We should probably keep up with the times and adjust the framework accordingly. I doubt that the versions are only there to publish bug fixes.

**Pull request closed without merging**
