### PR TITLE
Linux Filters Fix and BE README Update

### PR DESCRIPTION
**Pull request by trinitynet**
Modifications to the BE Filters names for linux support.

### CODE REVIEW

**Comment by trinitynet** [comment]
@BoGuu why u `Create publicvariablevar.txt` it is a pointless file

**Comment by Jawshy** [comment]
Ref: https://github.com/AsYetUntitled/Framework/pull/155

**Comment by BoGuu** [comment]
Because I like completeness. And in the case we want to add to it... ;)

**Comment by Jawshy** [comment]
B... But it doesn't do anything and never has ([[1]](https://github.com/DayZMod/Battleye-Filters/blob/Release_1.8.8/publicvariablevar.txt), [[2]](https://github.com/Pwnoz0r/DayZ-Private-Server/blob/master/cfgdayz/BattlEye/publicvariablevar.txt), [[3]](https://github.com/denisio/Dayz-Epoch-Linux-Server/blob/master/expansion/battleye/publicvariablevar.txt), and [[4]](http://opendayz.net/threads/a-guide-to-battleye-filters.21066/)). :confounded:

**Comment by BoGuu** [comment]
LGTM

**Comment by BoGuu** [comment]
[LGTM](https://lgtm.in/i/gAosEfO7q)

[:+1:](https://lgtm.in/u/gAosEfO7q) [:-1:](https://lgtm.in/r/gAosEfO7q)

**Comment by BoGuu** [comment]
[LGTM](https://lgtm.in/i/WDzcTNjYp)

[:+1:](https://lgtm.in/u/WDzcTNjYp) [:-1:](https://lgtm.in/r/WDzcTNjYp)

**Comment by BoGuu** [comment]
[LGTM](https://lgtm.in/i/WDzcTNjYp)

[:+1:](https://lgtm.in/u/WDzcTNjYp) [:-1:](https://lgtm.in/r/WDzcTNjYp)

**Comment by BoGuu** [comment]
LGTM

**Comment by Jawshy** [comment]
LGTM

**Comment by BoGuu** [comment]
LGTM

**Pull request merged**
