### PR TITLE
house blacklisting

### PR DESCRIPTION
**Pull request by SPS6**
Allows houses to be blocked from purchase buy adding the building's
objectID to a houseNoBuy array in the config_master.hpp. 

I thought that this might be useful for servers who would like to simply prevent the purchase of a particular house / houses which otherwise could be purchased by a player.

### CODE REVIEW

**Comment by SPS6** [comment]
Replaced tabs for CI check

**Comment by ColinM9991** [comment]
Has this been run by John (Paratus) to see if he's happy with his code being merged in?

**Comment by fresqo** [comment]
agreed, where is john john?

**Comment by SPS6** [comment]
I should imagine so baring in mind that it was present in 3.1.2 and I have simply re added it

**Comment by ColinM9991** [comment]
I don't remember this in 3.1.2, can this be confirmed?

This isn't a massive issue, but it's good to respect peoples development before merging in to see if they're okay with it.

**Comment by SPS6** [comment]
My mistake it was part of the build that @xmscx released updating the bruuudis housing script. https://web.archive.org/web/20160607225126/https://www.altisliferpg.com/topic/2894-howto-bruuudis-housing-script-in-313/ . I agree about respecting people's development hence I did not remove the credit.

**Comment by DomT602** [comment]
As we are unsure if the original owner (Paratus) has allowed this code to be merged here, this PR will be closed. If this is a feature people think belongs in the framework, feel free to make a new PR or an issue to be worked on for 6.x.

**Pull request closed without merging**
