### PR TITLE
BEFilters: Scripts: Add and Remove Exceptions

### PR DESCRIPTION
**Pull request by Jawshy**
#### Changes proposed in this pull request: 
- Added an exception to `ctrlDelete` in the scripts.txt BattlEye filter. 
  - scripts.log (output on client initialisation): 
```
DD.MM.YYYY HH:MM:DD: player (192.0.2.0:PORT) 12345678901234567890123456789012 - #4 "ts");
};



_ListGroup = _display displayctrl 		21903	;



ctrlDelete _ListGroup;
_listGroupCfg = configfile >> "RscDisplayDebri"
```

EDIT: 
- Removed an unused exception to `createDialog` in the scripts.txt BattlEye filter.

### CODE REVIEW

**Comment by SimZor** [comment]
LGTM 👍

**Comment by BoGuu** [comment]
Where is this from? It shouldn't only just be an issue now (dates back a year - google)

**Comment by Jawshy** [comment]
> Where is this from? It shouldn't only just be an issue now (dates back a year - google)

@BoGuu, the `altisPhone` exception should have been removed when the rest of the `altisPhone` code was removed, but the exception being left in the BEFilters didn't cause harm. It was just dead weight so to speak which is why I removed it.

**Comment by BoGuu** [comment]
I mean `Added an exception to ctrlDelete in the scripts.txt BattlEye filter.`

**Comment by Jawshy** [comment]
I only noticed the script restriction `#4` issue when I launched a recent vanilla build of the framework.

**Pull request merged**
