### PR TITLE
Resolved #171

### LINKED ISSUE #171: Tazing a cop/medic heals him
Just to point this out,this is a very low priority issue.

### Expected behaviour
The action gets ignored

### Actual behaviour
The tazer fully heals the target

### Steps to reproduce the behaviour 
1. Shoot a cop/medic with damage different from 0
2. He will get healed

https://github.com/AsYetUntitled/Framework/blob/master/Altis_Life.Altis/core/functions/fn_handleDamage.sqf#L43

----

Mission version: ~~Latest~~ v5.0.0 as of [a9681c7](https://github.com/AsYetUntitled/Framework/tree/a9681c74df08a9fea9614e2f528a196f636d9f30) 

Edit: Added exact mission version -- @Jawshy

### PR DESCRIPTION
**Pull request by BlackFisch**
<Please review the guidelines for contributing to this repository. The link is above.>

Resolves #171 . 

#### Changes proposed in this pull request: 
Fixed Tazer healing players

### CODE REVIEW

**Comment by BoGuu** [comment]
Why the global variable (and in survival too)? Just use the value given to you in handleDamage, please remember that `damage player` returns the value prior to the change (it awaits the EVH).

Regardless `_lastDamage` would error out as is ;)

**Comment by BlackFisch** [comment]
@BoGuu global variable simply because I sometimes had issues with the value passed by EVH and in survival just to be sure that the value is up-to-date. And it does not error out, I use this code since one month in my own mission without any problems.

**Comment by BoGuu** [comment]
@BlackFisch 

Firstly, survival runs every second (there is a HUGE room for error there), secondly, `_lastDamage` is undefined in survival. But either way, using the values in the EVH is absolutely fine (I've done it for a long time).

**Comment by BlackFisch** [comment]
Ahh, I see what you mean with the error, I forgot a line...
And by using EH you mean subtracting the value passed by EH from the damage value? But wouldn't that be inaccurate if you for example get hit by a nade and a shrapnel in the same frame? (nothing is impossible)

**Comment by BoGuu** [comment]
Sure, there is a slight room for error, but we are just trying to void the damage in specific circumstances. You can also check the hit part (and use getHit) to reduce that. Nether the less, using a one second delay on updating the damage will undoubtedly be prone to major inaccuracy.

**Comment by BlackFisch** [comment]
Yeah, that's an argument... didn't thought about that because i did edit the fn_survival a bit
nevertheless thanks for your time @BoGuu  :)

**Comment by BoGuu** [comment]
Any news on changing @BlackFisch ?

**Comment by BlackFisch** [comment]
Sorry BoGuu, not really. I don't have much time at the moment, exams and stuff... should get bettet at the weekend

**Comment by BoGuu** [comment]
@BlackFisch

Alright, np, just keep the PR updated with a status report, if this goes inactive for too long I'll close it.

**Comment by BlackFisch** [comment]
@BoGuu okay :) I will see if I can get it to work with what you mentioned

**Comment by BoGuu** [comment]
I have a complete - working well damage handler locally, if you hit me up on Discord, I'll send it to you (to work from).

**Comment by Jawshy** [comment]
Just a little note, you can hold off from updating the branch (Merge branch 'master' into issue171) until you need to make another commit or merge. Else there's just a flood of these merge branch commits.

**Comment by Jawshy** [comment]
Any updates on this... what is missing? Ping: @BlackFisch and @BoGuu.

**Comment by BoGuu** [comment]
Closing for now - see my Discord DM @BlackFisch

**Pull request closed without merging**
