### PR TITLE
Spyglass Updates.

### PR DESCRIPTION
**Pull request by Leigham**
Resolves https://github.com/AsYetUntitled/Framework/issues/383. EDIT: @Jawshy

This Should update all spyglass Patches, Variables and Functions to the latest arma update, and also fix the little error in the logs on launch, seemed to be checking for a variable before the variable was set.

### CODE REVIEW

**Comment by Leigham** [comment]
Ill take another look with my debug spyglass files :) xD

**Comment by BoGuu** [comment]
Any confirmation on this fixing the issue @Jawshy mentioned?

**Comment by Leigham** [comment]
It should fix the issue.

**Comment by AWildTeddyBear** [comment]
Note: I have tested this from a fresh pull of the framework with the changes from leigham. I can confirm all work. The only error that is thrown clientside is:
16:57:26 Fresnel n must be >0, given n=0,k=1.4

However, it does not break it, and I do not believe it deals with the current spyglass issues. 

PR GOOD. =D

**Comment by RosieCode95** [comment]
@Jawshy im not able to reproduce your issue, this PR works fine for me. can you recheck for me

**Comment by jordanlee833** [comment]
PEBCAC @Jawshy

**Comment by RosieCode95** [comment]
i got randomly kicked while tabbed out earllyer, not sure what the cause was as no logging. will boop it later some more

**Comment by jordanlee833** [comment]
Put into my mission, removes the admin error and patches are good.

**Comment by Jawshy** [comment]
@Wackbatt, @Jason2605, and I tested this pull request. We were all detected by SpyGlass within a minute of loading into the mission for a second time. No SpyGlass output in log files.

**Comment by AWildTeddyBear** [comment]
Working for me as well with multiple configurations.

**Comment by RosieCode95** [comment]
ive updated configs to the new arma build, requesting reviews if possible

**Comment by AWildTeddyBear** [comment]
Looks like all the errors that were chucked out when I tested, will test this later today though.

**Comment by AWildTeddyBear** [comment]
Definitely worked for me, adding in all the new stuff from the 1.72 update. One more to confirm and I think this will be good to merge everything. 🙃

**Comment by RosieCode95** [comment]
🎉 any issues please open a new PR

**Comment by jordanlee833** [comment]
🎊

**Pull request merged**
