### PR TITLE
Update fn_fetchPlayerHouses.sqf (never-ending pushback bug)

### PR DESCRIPTION
**Pull request by fresqo**
<Please review the guidelines for contributing to this repository. The link is above.>

Resolves #<issue ID here>. <If applicable.>
the _containerss array would muliply for ALL crates and keep updating the next house and the next house with multiple pushbacked crates. eventually if u have like 3 houses and 1 crate in each the third house would have all crates in its "containers" variable, disabling adding more crates due to limits.
#### Changes proposed in this pull request: 
- reassign the array by getting the "containers" variable each crate

### CODE REVIEW

**Comment by BoGuu** [comment]
Good spot. This file is absolutely horrible in general ;)

**Comment by setoy** [comment]
HC-Server is missing

**Comment by fresqo** [comment]
Could someone please double check for me the use of ...
missionNamespace setVariable [format ["houses_%1",_uid],_return];
i do not see a need for it.

**Comment by NiiRoZz** [comment]
It's my container system, when i was scripted this, i was dirty time, reworked all house system, more optimized ...

**Comment by fresqo** [comment]
So you will update the system? @NiiRoZz

**Comment by NiiRoZz** [comment]
@fresqo i'm working, on it, yes

**Comment by BoGuu** [comment]
Will clean the file up in due course. Thanks!

**Pull request merged**
