### PR TITLE
Added panic button v-item for police

### PR DESCRIPTION
**Pull request by robinwithes**
Added a v-item called panic button which when used sends a emergency broadcast to the police as well as marking the location of the cop in distress to them.

- [ ] I have tested my changes and corrected any errors found

### CODE REVIEW

**Comment by robinwithes** [comment]
Not sure what the checkstyle issue is here

**Comment by imthatguyhere** [comment]
> Not sure what the checkstyle issue is here

Put a space between `if` and `(` on the two lines noted.

**Comment by SimZor** [comment]
Yeez

**Comment by DomT602** [comment]
Hi @robinwithes, firstly thanks for the PR, when it comes to this feature; we believe it be left to server owners to implement this how they want, in order to make their server unique. This would be more suited to being on a separate public repository where you could release these scripts as small addons that server owners can add if they want. We have had similar situations, namely this https://github.com/AsYetUntitled/Framework/issues/111#issuecomment-252308203.
With this in mind, I'll be closing this PR.

**Pull request closed without merging**
