### PR TITLE
#96 Fix wrong param expect data for civ_alive

### PR DESCRIPTION
**Pull request by macchky**
#96

### CODE REVIEW

**Comment by setoy** [comment]
Aren't you missing out the HC?

**Comment by macchky** [comment]
Oh. Re pull request

**Comment by macchky** [comment]
Added

**Comment by BoGuu** [comment]
@macchky 
Sorry this is delayed, have been incredibly busy.

You are indeed right about the expected type being wrong, however, this surprisingly has no implication.

The smart cookie who added the position saving into the build decided not to use the variable defined, instead using the raw data from the variables passed.

**Pull request merged**
