### PR TITLE
Fixed: Instant Revival if outside distance

### PR DESCRIPTION
**Pull request by Scarso327**
We have a drag option on our server and when someone was taken outside this range the isNil check didn't work and so it would instantly revive the player without stopping it at the line 67 exitWith.

- [x] I have tested my changes and corrected any errors found

### CODE REVIEW

**Comment by Scarso327** [comment]
Dunno if I did a good or not :p Just update stuff from what I interrupted your review to mean.

**Comment by DomT602** [comment]
@Scarso327 thats pretty good so far 👍 Just one last thing, we can change; private _target = param [0,objNull,[objNull]];
to; params [
    ["_target",objNull,[objNull]
];

**Comment by Scarso327** [comment]
Done. Is parmas faster or something?

**Comment by Leigham** [comment]
@Scarso327  Params is newer.

**Comment by Leigham** [comment]
`if !(params [
    ["_target",objNull,[objNull]]
]) exitWith {};`

you had an error, if you use this, you can also remove the `if (isNull _target) exitWith {}` line

**Comment by Leigham** [comment]
@Scarso327  please read what I put.
you cant just remove the line

**Comment by Scarso327** [comment]
Sorry, I am jumping between server work and this. What you said was hard to understand until the "also" part

**Comment by Leigham** [comment]
params returns a boolean, meaning, if the data doesn't match the type, or its default, it will return `true` so if you put `if !(params [blah]) exitWith` it will exit the script if it is default values.

**Comment by Scarso327** [comment]
But is isNull check before already did that?

**Comment by Leigham** [comment]
why have an error uneeded line ?

**Comment by Scarso327** [comment]
OH, I UNDERSTAND

**Comment by Jason2605** [comment]
Good spot 👍

**Pull request merged**
