### PR TITLE
Updated for tanks DLC

### PR DESCRIPTION
**Pull request by Leigham**
Resolves #. 

#### Changes proposed in this pull request: 
- 

- [x] I have tested my changes and corrected any errors found

### CODE REVIEW

**Comment by Leigham** [comment]
Seems to work. no kicks as of yet

**Comment by BoGuu** [comment]
Thanks for the PR :+1:

I've cleaned up the file and some of the changes, could you double check them (and check if it works on your build?) @Leigham

**Comment by Leigham** [comment]
will do.

**Comment by BoGuu** [comment]
Any news @Leigham ?

**Comment by Leigham** [comment]
Sorted 👍

**Comment by Jason2605** [comment]
Thanks!

**Pull request merged**
