### PR TITLE
Add some textures for apex vehicle

### PR DESCRIPTION
**Pull request by Nark0t1k**
#### Changes proposed in this pull request: 
- And some texture for 
C_Scooter_Transport_01_F
C_Offroad_02_unarmed_F
C_Plane_Civil_01_F

Some texture name from C_Plane_Civil_01_F was in french :$

### CODE REVIEW

**Comment by Nark0t1k** [comment]
Tab replaced
Texture translate to english name

**Comment by Jawshy** [comment]
Travis CI is [still detecting indenting with tabs](https://travis-ci.org/AsYetUntitled/Framework/builds/182552259).

**Comment by Nark0t1k** [comment]
Tab replaced
Name translate

**Comment by Jawshy** [comment]
Thanks, @Nark0t1k.

**Comment by BoGuu** [comment]
LGTM

**Comment by Jawshy** [comment]
LGTM

**Pull request merged**
