### PR TITLE
replace == to isEqualTo

### PR DESCRIPTION
**Pull request by WolfSkin1337**
replace == to isEqualTo

Resolves #. 

#### Changes proposed in this pull request: 
- 

- [ ] I have tested my changes and corrected any errors found

### CODE REVIEW

**Comment by klmunday** [comment]
There are several reasons as to why `==` is still used in some files. Although in some places `isEqualTo` may be more beneficial. 

https://community.bistudio.com/wiki/isEqualTo

I think it would be a lot of work to manually test that everything functions as intended with these changes. I remember PRs in the past replacing every instance of `==` in the past had several comments with specific reasons for some usages

**Comment by cryptearth** [comment]
> I think it would be a lot of work to manually test that everything functions as intended with these changes.

I'd love to help with this - but I only have access to one steam account with Arma3 in it - and unfortunately most of my friends who also have it aren't interested in development of the framework but rather only prefer some fast quick dirty shootouts on some random server. I'll have to see to maybe get at least another copy for a rather cheap offer so I can test at least player-interaction on my own.
So, if anyone wants to collab on it I'm in for it ...

**Comment by IceEagle132** [comment]
You can run an Arma 3 server without owning Arma 3...

**Comment by cryptearth** [comment]
It's not about getting the server binaries and run it but rather having to players on it at the same time using two computers. As for now sure I can join my server by myself (although it's open to public and by the database I already had a few "short time" visitors) but I can't do any testing on player-to-player interaction like sharing the key for a car/house (so I would had never been able to spot the error in PR #662 just by playing). Likewise I can'T test any cop-med-civ interaction like reviving a dead player or taking a rebel into custody or a prison breakout (although for that I would need at least 3 players: one in jail, one help with the breakout and one cop) - I just don't have to money to spent to buy additional arma3 keys right now.

**Comment by klmunday** [comment]
> It's not about getting the server binaries and run it but rather having two (or more) players on it at the same time using two (or more) computers. As for now sure I can join my server by myself (although it's open to public and by the database I already had a few "short time" visitors) but I can't do any testing on player-to-player interaction like sharing the key for a car/house (so I would had never been able to spot the error in PR #662 just by playing). Likewise I can'T test any cop-med-civ interaction like reviving a dead player or taking a rebel into custody or a prison breakout (although for that I would need at least 3 players: one in jail, one help with the breakout and one cop) - I just don't have to money to spent to buy additional arma3 keys right now.

You can host a server locally and connect with multiple local clients from the same pc. Look into the loopback setting in the  arma server config

**Comment by WolfSkin1337** [comment]
its a fail

**Comment by cryptearth** [comment]
> You can host a server locally and connect with multiple local clients from the same pc. Look into the loopback setting in the arma server config

Neat idea - but how? When I try to start ArmA3 a 2nd time the currently running instance just gets killed instantly. Also: As AL depends on unique player IDs: When starting multiple instance the all would end up with the same player ID - which may can lead to other issues I guess?

**Comment by klmunday** [comment]
> > You can host a server locally and connect with multiple local clients from the same pc. Look into the loopback setting in the arma server config
> 
> Neat idea - but how? When I try to start ArmA3 a 2nd time the currently running instance just gets killed instantly. Also: As AL depends on unique player IDs: When starting multiple instance the all would end up with the same player ID - which may can lead to other issues I guess?

I used to just start the server as usual, then launch the arma3 executable twice, Once through Steam, not sure if that's significant or not. Didn't run into issues in-game when doing things

**Comment by Azeh** [comment]
> > You can host a server locally and connect with multiple local clients from the same pc. Look into the loopback setting in the arma server config
> 
> Neat idea - but how? When I try to start ArmA3 a 2nd time the currently running instance just gets killed instantly.

Disable client BattlEye.

**Comment by cryptearth** [comment]
Hmm, tried, but no matter how I try to start the 2nd ArmA3 instance it instantly kills the current running one - I guess I just do something wrong or stupid (both maybe).

**Comment by Azeh** [comment]
> Hmm, tried, but no matter how I try to start the 2nd ArmA3 instance it instantly kills the current running one - I guess I just do something wrong or stupid (both maybe).

image

**Comment by cryptearth** [comment]
> > Hmm, tried, but no matter how I try to start the 2nd ArmA3 instance it instantly kills the current running one - I guess I just do something wrong or stupid (both maybe).
> 
> image

That's what I tried. I also tried to launch arma3 directly without steam or its battleye loader - but doesn't seem to make any difference. Can't get a 2nd ArmA3 game to launch ...

**Comment by klmunday** [comment]
This has gone off topic, to avoid email spam please continue this either privately or via our Discord server

**Pull request closed without merging**
