### PR TITLE
Add Apex Backpack

### PR DESCRIPTION
**Pull request by Nark0t1k**
<Please review the guidelines for contributing to this repository. The link is above.>

Resolves #<issue ID here>. <If applicable.>

#### Changes proposed in this pull request: 
- Allow ApexBackPack type: tna

### CODE REVIEW

**Comment by Nark0t1k** [comment]
Tested but maybe need some more test because i also need to add
ghex
for
B_FieldPack_ghex_f
B_Carryall_ghex_f

tna is for
B_AssaultPack_tna_f

(only for apex clothing config)

**Comment by Nark0t1k** [comment]
Add
tna and ghex
Also edit addbackpackcargo here
https://github.com/AsYetUntitled/Framework/pull/204

**Comment by Jawshy** [comment]
Why are https://github.com/AsYetUntitled/Framework/pull/204 and this separate pull requests? You can change more than one file per PR. :wink:

**Comment by Nark0t1k** [comment]
@Jawshy 
Pull createvehicle first then try to add second file but pull request was already done and don't find how attach second file to first pull request :/

**Comment by BoGuu** [comment]
LGTM

**Comment by Jawshy** [comment]
LGTM

**Pull request merged**
