### PR TITLE
Move life_fnc_terrainSort to serverSide (TON_fnc_terrainSort)

### LINKED ISSUE #144: life_fnc_terrainsort isn't server side
<Please review the guidelines for contributing to this repository. The link is above.>
<If you are reporting a bug then you must use the provided issue template.>

### Expected behaviour
No errors.

### Actual behaviour
Error Undefined variable in expression: life_fnc_terrainsort

### Steps to reproduce the behaviour 
1. TerrainSort serverside

### [RPT]http://hastebin.com/uqebifogeb.css

Just need to make it ServerSide
----

Mission version: <See core/init.sqf, briefingName in mission.sqm, or changelog in briefing.sqf for your mission version.>

Launcher version: <In the Arma 3 launcher go to ⚙ OPTIONS and click the version info below to copy it to your clipboard.>

Game version: 

Branch:

### PR DESCRIPTION
**Pull request by SimZor**
Resolves #144 

#### Changes proposed in this pull request: 
- Moved terrainSort function to serverSide
- life_fnc_terrainSort -> TON_fnc_terrainSort
- Change life_fnc_terrainsort in SpyGlass config to SERVER_Functions (ton_fnc_terrainsort)

### CODE REVIEW

**Comment by setoy** [comment]
I don't have said problem (#144) on my test server, how's that possible?

**Comment by SimZor** [comment]
@setoy I dunno, @BoGuu just asked to make a issue about it so I thought I'd do a pull request regardless.

I didn't have any problems either.

**Comment by Jawshy** [comment]
The following was not removed, @SimZor: 

Altis_Life.Altis/[Functions.hpp, line 208](https://github.com/AsYetUntitled/Framework/blob/7344c21ea24a85c162bf8e675c02594915c563bd/Altis_Life.Altis/Functions.hpp#L208)
```cpp
        class terrainSort {};
```

**Comment by SimZor** [comment]
Fixed @Jawshy

**Comment by Jason2605** [comment]
https://github.com/AsYetUntitled/Framework/blob/master/life_server/init.sqf#L181-L184

**Comment by SimZor** [comment]
fixed @Jason2605

**Comment by Jawshy** [comment]
@SimZor, look again. :wink:

**Comment by SimZor** [comment]
fixed @Jawshy

**Comment by BoGuu** [comment]
`ton_fnc_terrainsort_meta`

**Comment by SimZor** [comment]
Done, @BoGuu.

**Pull request merged**
