### PR TITLE
createVehice > createVehicleLocal

### PR DESCRIPTION
**Pull request by luudvkeulen**
<Please review the guidelines for contributing to this repository. The link is above.>

Resolves #<issue ID here>. <If applicable.>

#### Changes proposed in this pull request: 
- Vehicle 3D preview optimization.

No need to create the vehicle in mp.

### CODE REVIEW

**Comment by Jawshy** [comment]
`life_preview_light` used to be `createVehicleLocal` but was changed to `createVehicle`. See https://github.com/AsYetUntitled/Framework/commit/21dac05361da783f8bf348a34d3c0c4a8c3ec550.

**Comment by luudvkeulen** [comment]
Why was is changed to createVehicle?

**Comment by Emma-L** [comment]
@luudvkeulen 

Like Jawshy said:
> See [21dac05](https://github.com/AsYetUntitled/Framework/commit/21dac05361da783f8bf348a34d3c0c4a8c3ec550) 

It was to stop it spamming logs.

**Comment by BoGuu** [comment]
We'll double check for another way to remove the spam (the issue is gone now, can't really remember, @Jawshy ?). I pretty sure I said performance > spam in the last issue

**Comment by luudvkeulen** [comment]
I had spam because of the remotexec that is why I changed it to createvehiclelocal. No spam anymore...

**Comment by Jawshy** [comment]
Server administrators can omit `life_fnc_hideObj` from the [`remoteExec`](https://github.com/AsYetUntitled/Framework/blob/87eea05ab2cd6e5d3d59197d15c717bf8f32671d/BEFilters/remoteExec.txt) logs by changing the following: 

```
1 "" !="_this call fn_whoDoneIt"
```

↓

```
1 "" !="_this call fn_whoDoneIt" !life_fnc_hideObj
```

If I correctly recall, using `createVehicleLocal` generated spam entries in the [arma3.rpt](https://community.bistudio.com/wiki/Crash%20Files) (client) file. 

remoteexec.log: 

```
04.10.2016 12:23:02: Jawsh (10.0.0.7:2316) - #0 "life_fnc_hideobj [<NULL-object>]"
04.10.2016 12:23:02: Jawsh (10.0.0.7:2316) - #0 "life_fnc_hideobj [1814912: <no shape>]"
04.10.2016 12:23:06: Jawsh (10.0.0.7:2316) - #0 "life_fnc_hideobj [22a19600# 1814931: heli_light_01_f.p3d REMOTE]"
04.10.2016 12:23:06: Jawsh (10.0.0.7:2316) - #0 "life_fnc_hideobj [1814912: <no shape>]"
```

**Comment by BoGuu** [comment]
@Jawshy 

Wasn't it something to do with parachutes or what not?

**Comment by Jawshy** [comment]
Who knows, @BoGuu. The original issue and pull request were many months ago. I do know that previewing a helicopter creates multiple backpack entries as they have parachutes in their inventory by default.

**Comment by BoGuu** [comment]
Sorry for the huge delay. Will merge and fix any log issues

**Pull request merged**
