### PR TITLE
dialog: switch to Roboto & minor fixes

### PR DESCRIPTION
**Pull request by danielstuart14**
Arma is using Roboto as default font, now.

#### Changes proposed in this pull request: 
- Fix space in HUD
- Fix clothing slidebar position
- Change default font from Purista to Roboto

### CODE REVIEW

**Comment by BoGuu** [comment]
LGTM - as long as this font looks nice :)

**Comment by SimZor** [comment]
@BoGuu Nothing is worse then the default font :rofl:

**Comment by Jawshy** [comment]
@danielstuart14 https://github.com/AsYetUntitled/Framework/pull/218#pullrequestreview-14889395

**Comment by danielstuart14** [comment]
I'll add an image.

**Comment by danielstuart14** [comment]
![purista vs roboto] (http://i.imgur.com/RNb0x8C.jpg)

The new one is the Arma's official font. 
https://forums.bistudio.com/topic/188246-poll-new-update-regarding-new-font-and-sound/

**Comment by WolfSkin1337** [comment]
The new one is very nice to see.

**Comment by NeFShARk** [comment]
Indeed, it looks better.

**Comment by danielstuart14** [comment]
I enjoy it more than the Purista but, it still isn't perfect.
The best thing is that Roboto is much narrower than Purista. (More info in the same space)

**Comment by Jawshy** [comment]
LGTM

**Pull request merged**
