### PR TITLE
Set playerSurrender variable to false in fn_restarinAction

### LINKED ISSUE #248: Restrain glitch
<Please review the guidelines for contributing to this repository. The link is above.>
<If you are reporting a bug then you must use the provided issue template.>

### Expected behaviour
When having your hands up(surrender) and a cop restrains you it should make the restrain animation

### Actual behaviour
Your hands are still up and it wont do the restrain animation

### Steps to reproduce the behaviour 
1. surrender
2. get a cop to restrain you

### [RPT](https://community.bistudio.com/wiki/Crash_Files#Arma_3) and/or extDB2 logs (if applicable)
<Check your client and server RPT and extDB2 logs for errors and warnings.>
<If there are relevant messages and they are short then post them here with code formatting.>
<If there are relevant messages and they are long then upload the whole file to GitHub, Pastebin, or Hastebin.>

----

Mission version: <See core/init.sqf, briefingName in mission.sqm, or changelog in briefing.sqf for your mission version.> 5,0

Launcher version: <In the Arma 3 launcher go to ⚙ OPTIONS and click the version info below to copy it to your clipboard.> latest

Game version: latest

Branch: 5,0

### PR DESCRIPTION
**Pull request by Blauschimmel**
Resolves #248 . 

#### Changes proposed in this pull request: 
- Simply added `_unit setVariable ["playerSurrender",false,true];`

### CODE REVIEW

**Comment by SimZor** [comment]
hands wont be taken down by just setting a var to false if that is what you want to do

**Comment by Blauschimmel** [comment]
Why not? This would end the loop in the actions/fn_surrender.sqf... And it actually works im my test...

**Comment by SimZor** [comment]
Sorry mate, my bad. Didn't see that it looped while that variable was true. Apologies.

**Comment by BoGuu** [comment]
Thanks for the PR :)

**Pull request merged**
